// Configuration for the Claude AI File Uploader Extension

// Allowed file extensions
export const ALLOWED_EXTENSIONS = new Set([
	// Documentation and Text
	'pdf',
	'doc',
	'docx',
	'txt',
	'rtf',
	'odt',
	'md',
	'markdown',
	'tex',
	'latex',
	'wiki',
	'rst',
	'adoc',
	'log',
	'msg',
	'pages',
	'epub',
	'mobi',
	'azw3',
	'djvu',
	// Web Development
	'html',
	'htm',
	'xhtml',
	'css',
	'scss',
	'sass',
	'less',
	'styl',
	'js',
	'jsx',
	'ts',
	'tsx',
	'vue',
	'svelte',
	'php',
	'asp',
	'aspx',
	'jsp',
	'cshtml',
	'wasm',
	'wat',
	'webmanifest',
	'htaccess',
	'htpasswd',
	'ejs',
	'hbs',
	'handlebars',
	'pug',
	'jade',
	'haml',
	'liquid',
	// Programming Languages
	'py',
	'pyc',
	'pyo',
	'pyd',
	'pyw',
	'ipynb',
	'java',
	'class',
	'jar',
	'war',
	'cpp',
	'cc',
	'cxx',
	'c',
	'h',
	'hpp',
	'hxx',
	'cs',
	'csx',
	'vb',
	'fs',
	'fsx',
	'rb',
	'rbw',
	'rake',
	'gemspec',
	'swift',
	'swiftmodule',
	'kt',
	'kts',
	'go',
	'mod',
	'rs',
	'rlib',
	'scala',
	'sc',
	'clj',
	'cljs',
	'cljc',
	'edn',
	'erl',
	'hrl',
	'ex',
	'exs',
	'hs',
	'lhs',
	'lua',
	'luac',
	'pl',
	'pm',
	'pod',
	't',
	'r',
	'rdata',
	'rds',
	'rmd',
	'matlab',
	'm',
	'fig',
	'mat',
	'f',
	'f90',
	'f95',
	'f03',
	'f08',
	'pas',
	'pp',
	'groovy',
	'gvy',
	'gy',
	'gsh',
	'd',
	'jl',
	'dart',
	'elm',
	'coffee',
	'litcoffee',
	'ls',
	'livescript',
	'nim',
	'ml',
	'mli',
	'mll',
	'mly',
	// Shell and Scripts
	'sh',
	'bash',
	'zsh',
	'fish',
	'csh',
	'ksh',
	'bat',
	'cmd',
	'ps1',
	'psm1',
	'psd1',
	'awk',
	'sed',
	'tcl',
	'expect',
	// Database and Query Languages
	'sql',
	'mysql',
	'pgsql',
	'plsql',
	'sqlite',
	'mongodb',
	'cypher',
	'sparql',
	'hql',
	'prisma',
	// Data Formats
	'xml',
	'json',
	'yaml',
	'yml',
	'toml',
	'csv',
	'tsv',
	'ods',
	'xls',
	'xlsx',
	'numbers',
	'proto',
	'avro',
	'parquet',
	'thrift',
	'graphql',
	'gql',
	// Configuration Files
	'ini',
	'conf',
	'config',
	'cfg',
	'properties',
	'env',
	'dist',
	'local',
	'docker',
	'dockerfile',
	'dockerignore',
	'vagrantfile',
	'buildpack',
	'gitignore',
	'gitattributes',
	'editorconfig',
	'eslintrc',
	'prettierrc',
	'stylelintrc',
	'babelrc',
	'npmrc',
	'yarnrc',
	'nvmrc',
	'gradle',
	'pom',
	'ivy',
	'ant',
	'cmake',
	'make',
	'mak',
	'makefile',
	'kubernetes',
	'helm',
	'terraform',
	'tf',
	'vcxproj',
	'csproj',
	'sln',
	'pbxproj',
	// IDEs and Editors
	'vim',
	'vimrc',
	'gvimrc',
	'ideavimrc',
	'vscode',
	'sublime-project',
	'sublime-workspace',
	'workspace',
	'project',
	'code-workspace',
	// Template Files
	'tpl',
	'tmpl',
	'template',
	'mustache',
	'nunjucks',
	'njk',
	'jinja',
	'j2',
	'erb',
	'eex',
	'leex',
	'swig',
	// Build Output
	'map',
	'min',
	'bundle',
	'pack',
	// 'dist', // Already in DOT_FOLDERS
	'out', // Already in DOT_FOLDERS
	'build', // Already in DOT_FOLDERS
	'release',
	// Security and Certificates
	'pem',
	'crt',
	'ca-bundle',
	'p12',
	'pfx',
	'key',
	'keystore',
	'csr',
	'cert',
	// Game Development
	'unity',
	'unitypackage',
	'prefab',
	'asset',
	'blend',
	'blend1',
	'fbx',
	'obj',
	'mtl',
	'gltf',
	'glb',
	'uasset',
	'umap',
	// Machine Learning
	'onnx',
	'pkl',
	'joblib',
	'h5',
	'hdf5',
	'pb',
	'pbtxt',
	'ckpt',
	'model',
	// Cloud and Serverless
	'aws',
	'azure',
	'gcp',
	'cloudformation',
	'sam',
	'serverless',
	'netlify',
	'vercel',
]);

// Folders to exclude (typically hidden folders)
export const DOT_FOLDERS = new Set([
	'.next',
	'.git',
	'.github',
	'.vscode',
	'.idea',
	'.DS_Store',
	'.vs',
	'.cache',
	'.npm',
	'.yarn',
	'__pycache__',
	// Added from the original subtask description
	'.svn',
	'.hg',
	'.project',
	'.settings',
	'node_modules',
	'target',
	'build',
	'dist',
	'out',
	'bin',
	'obj',
	'.gradle',
	'.pytest_cache',
	'.mypy_cache',
	'.tox',
	'.env',
	'.venv',
	'venv',
	'ENV',
	'env',
	'migrations'
]);

// Critically excluded dotfolders when "Include hidden files/folders" is checked.
// These are typically version control system metadata folders.
export const CRITICAL_DOT_FOLDERS = new Set([
	'.git',
	'.svn', // Subversion
	'.hg',  // Mercurial
]);

// Common text-based file extensions suitable for concatenation
export const TEXT_FILE_EXTENSIONS = new Set([
	// Plain Text & Markdown
	'txt', 'md', 'markdown', 'rtf', 'log', 'srt', 'vtt', 'tex', 'text',
	// Programming & Scripting
	'py', 'js', 'jsx', 'ts', 'tsx', 'java', 'c', 'cpp', 'h', 'hpp', 'cs', 
	'sh', 'bash', 'zsh', 'rb', 'php', 'pl', 'pm', 'swift', 'go', 'rs', 'lua',
	'scala', 'kt', 'kts', 'groovy', 'dart', 'pas', 'f', 'f90', 'f95', 'f03', 'f08',
	'ps1', 'psm1', 'psd1', 'tcl', 'awk', 'sed', 'asm', 's',
	// Web Development
	'html', 'htm', 'xhtml', 'css', 'scss', 'sass', 'less', 'styl', 'vue', 'svelte',
	'webmanifest', 'htaccess', 'htpasswd', 'ejs', 'hbs', 'handlebars', 'pug', 'jade', 'haml', 'liquid',
	// Data Formats
	'json', 'xml', 'yaml', 'yml', 'toml', 'csv', 'tsv', 'ini', 'conf', 'config', 'cfg', 'properties', 'env',
	'sql', 'graphql', 'gql', 'proto', 'prisma',
	// IDE/Editor specific (often text-based)
	'gitignore', 'gitattributes', 'editorconfig', 'eslintrc', 'prettierrc', 'stylelintrc', 'babelrc', 
	'npmrc', 'yarnrc', 'nvmrc', 'dockerfile', 'vagrantfile', 'makefile', 'mak', 'cmake',
	'csproj', 'vbproj', 'sln', 'vcxproj', 'pbxproj', 'podspec', 'gemspec',
	// Other
	'sub', 'ass', // Subtitles
	'rss', 'atom', 'opml',
	// Note: Some files like .ipynb are JSON but often large/complex for simple concat. Included for now.
	'ipynb', 
]);
